### ISSUE TITLE
Why use siphasher?

### ISSUE THREAD

**Issue by FilipAndersson245** [typst/comemo#3]
Hello,
I was just wondering why specificaly this library use siphash as the default hashing algorithm?
As we hash u128 I think `ahash` would be a good alternative as it seem to be upwards of 20x faster for those sizes

![image](https://github.com/typst/comemo/assets/17986183/4fbd7ede-f837-49bd-ab26-b4190e0227b2)

**Comment by laurmaedje** [comment]
We need collision resistance because we assume that hash collisions never happen. I don't know about aHash, but FnvHash and FxHash are not designed for such use cases. The decision to use SipHash follows rustc's incremental compiler: https://github.com/rust-lang/rust/pull/107925

**Comment by FilipAndersson245** [comment]
It seem as ahash would not be suitable then, they use a u64 hash, but their hash quality seem to be better then FX.

**Comment by briansmith** [comment]
> We need collision resistance because we assume that hash collisions never happen. I don't know about aHash, but FnvHash and FxHash are not designed for such use cases. 

SipHash128 is not a collision-resistant hash function. If you read the original SipHash whitepaper they even say that it is "obvious" that it is not. 

> The decision to use SipHash follows rustc's incremental compiler: [rust-lang/rust#107925](https://github.com/rust-lang/rust/pull/107925)

See https://github.com/rust-lang/rust/issues/10389 for extensive discussion.

From your source code:
https://github.com/typst/comemo/blob/1275982a62a0815c9ca5a0d734ef5883c4178fc1/src/prehashed.rs#L22-L27
Even when used with a CSPRNG-provided random key, the original use case for SipHash was hash functions, which do a full equality check done after the hash equality check, to verify there are no collisions.

**Comment by laurmaedje** [comment]
The idea here isn't that an attacker can't find a collision, but rather than we don't run into a collision accidentally. Reading this comment https://github.com/rust-lang/rust/issues/10389#issuecomment-1887239511, it appears that 128-bit SipHash gives us that.

**Comment by laurmaedje** [comment]
I admit that the docs don't make that fully clear.
